csp/urls.py
from django.conf.urls import include, url
from django.conf.urls import url
from django.contrib import admin
from cspapp.views import*
from django.conf.urls import patterns
from django.contrib.auth.views import login, logout
from cspapp.views import *
from cspapp import views


from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', mainpage),
    url(r'^cspapp/', include('cspapp.urls', namespace = 'cspapp')),
    url(r'^accounts/login/$', login, name='login'),
    url(r'^accounts/logout/$', logout, name='logout'),

    url('^register/', CreateView.as_view(
        template_name='register.html',
        form_class=UserCreationForm,
        success_url='http://127.0.0.1:8000/'),name='register'),

    url(r'^delete_project/(?P<rest_pk>\d+)/$', views.delete_project, name='delete_project'),
    url(r'^delete_comment/(?P<rest_pk>\d+)/$', views.delete_comment, name='delete_comment'),
    url(r'^delete_activity/(?P<rest_pk>\d+)/$', views.delete_activity, name='delete_activity'),
    url(r'^delete_answer/(?P<rest_pk>\d+)/$', views.delete_answer, name='delete_answer'),

    url(r'^profile/(?P<rest_pk>\d+)/$', views.profile, name='profile'),
    #url(r'profile/', profile),



]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, })
    ]

cspapp/urls.py
from views import *
from django.conf.urls import url
from django.views.generic import DetailView, ListView, UpdateView

urlpatterns = [
    url(r'^projects/$',
        ProjectsList.as_view(),
        name='projects_list'),

    url(r'^users/$',
        UsersList.as_view(),
        name='users_list'),



    url(r'^projects/create/$',
        ProjectCreate.as_view(),
        name='project_create'),

    url(r'^projects/(?P<pk>[a-zA-Z0-9 ]+)/$',
        ProjectsDetail.as_view(),
        name='projects_detail'),

    url(r'^projects/(?P<pk>[a-zA-Z0-9 ]+)/edit/$',
        UpdateView.as_view(
            model=Project,
            template_name='cspapp/form.html',
            form_class=ProjectForm),
        name='project_edit'),

    url(r'^projects/(?P<pk>[a-zA-Z0-9 ]+)/activities/$',
        ActivityList.as_view(),
        name='activity_list'),




    url(r'^projects/(?P<pk>[a-zA-Z0-9 ]+)/activities/create/$',
        ActivityCreate.as_view(),
        name='activity_create'),

    url(r'^activities/(?P<pk>[a-zA-Z0-9 ]+)/$',
        ActivityDetail.as_view(),
        name='activities_detail'),


    url(r'^activities/(?P<pk>[a-zA-Z0-9 ]+)/edit$',
        UpdateView.as_view(
            model=ProjectActivity,
            template_name='cspapp/form.html',
            form_class=ActivityForm),
        name='activity_edit'),

    url(r'^activities/(?P<pk>[a-zA-Z0-9 ]+)/create/$',
        answer,
        name='answer_create'),

    url(r'^projects/(?P<pk>[a-zA-Z0-9 ]+)/reviews/create/$',
        review,
        name='review_create'),
]

cspapp/forms.py
from django.forms import ModelForm
from models import *
from django import forms


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        exclude = ('author', 'project',)


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        exclude = ()


class PostForm(forms.ModelForm):

        class Meta:
            model = User
            fields = ('username', 'password' ,'email',)


class ActivityForm(forms.ModelForm):
    class Meta:
        model = ProjectActivity
        exclude = ('user', 'date', 'creator',)

#NO SE USA EN EL REGISTER, SERVIRA PARA INSERTAR POSTS

cspapp/views.py
from django.views.generic import DetailView, ListView
from django.http import HttpResponse
from django.views.generic.base import TemplateResponseMixin
from django.core import serializers
from django.shortcuts import render
from django.views.generic.edit import CreateView
from forms import *
from models import *
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse, reverse_lazy
from django.utils import timezone

# Create your views here.

def mainpage(request):
    return render(request, 'cspapp/principal.html')

def profile(request,rest_pk):
    profile = User.objects.get(id=rest_pk)
    #projects = Project.objects.all()
    #return render(request, 'cspapp/profile.html', {'projects' : projects} )
    #return render(request, 'cspapp/profile.html', {'profile': profile})
    projects = Project.objects.all()

    context = {'profile': profile, 'projects': projects}
    return render(request, 'cspapp/profile.html', context=context)


class ProjectsList(ListView):
    model = Project
    queryset = Project.objects.all()
    context_object_name = 'projects'
    template_name = 'cspapp/projects_list.html'



class UsersList(ListView):
    model = User
    queryset = User.objects.all()
    context_object_name = 'users'
    template_name = 'cspapp/users_list.html'

class ProjectsDetail(DetailView):
    model = Project
    context_object_name = 'project'
    template_name = 'cspapp/projects_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ProjectsDetail, self).get_context_data(**kwargs)
        context['RATING_CHOICES'] = ProjectReview.RATING_CHOICES
        return context


class ProjectCreate(CreateView):
    model = Project
    template_name = 'cspapp/form.html'
    form_class = ProjectForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(ProjectCreate, self).form_valid(form)


def delete_project(request,rest_pk):
    delRest= Project.objects.get(pk=rest_pk)
    delRest.delete()
    return redirect('http://127.0.0.1:8000/cspapp/projects/')


class ActivityDetail(DetailView):
    model = ProjectActivity
    context_object_name = 'activity'
    template_name = 'cspapp/activity_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ActivityDetail, self).get_context_data(**kwargs)
        return context



class ActivityCreate (CreateView):
    models = ProjectActivity
    template_name = 'cspapp/form.html'
    form_class = ActivityForm

    def form_valid(self, form):
        form.instance.creator = self.request.user
        return super(ActivityCreate, self).form_valid(form)


class ActivityList(ListView):
    model = Activity
    queryset = Activity.objects.all()
    context_object_name = 'activities'
    template_name = 'cspapp/activities_list.html'


def answer(request, pk):
    act = get_object_or_404(Activity, pk=pk)
    answer = ActivityAnswer(
        body=request.POST['comment'],
        user=request.user,
        project=act)
    answer.save()
    return HttpResponseRedirect(reverse('cspapp:activities_detail', args=(act.id,)))


class CommentCreate (CreateView):
    models = Comment
    template_name = 'cspapp/form.html'
    form_class = CommentForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(CommentCreate, self).form_valid(form)


class CommentList(ListView):
    model = Comment
    queryset = Comment.objects.all()
    context_object_name = 'comments'
    template_name = 'cspapp/comment_list.html'


def review(request, pk):
    project = get_object_or_404(Project, pk=pk)
    review = ProjectReview(
        rating=request.POST['rating'],
        comment=request.POST['comment'],
        user=request.user,
        project=project)
    review.save()
    return HttpResponseRedirect(reverse('cspapp:projects_detail', args=(project.id,)))


def delete_comment(request, rest_pk):
    delRest= Review.objects.get(pk=rest_pk)
    projetpk = ProjectReview.objects.get(pk=rest_pk).project
    delRest.delete()
    return redirect(reverse_lazy('cspapp:projects_detail', kwargs={'pk':projetpk.id}))


def delete_answer(request, rest_pk):
    ans = Answer.objects.get(pk=rest_pk)
    activity = ActivityAnswer.objects.get(pk=rest_pk).project
    ans.delete()
    return redirect(reverse_lazy('cspapp:activities_detail', kwargs={'pk':activity.id}))




def delete_activity(request, rest_pk):
    ans = ProjectActivity.objects.get(pk=rest_pk)
    projetpk = ProjectActivity.objects.get(pk=rest_pk).project
    ans.delete()
    return redirect(reverse_lazy('cspapp:projects_detail', kwargs={'pk':projetpk.id}))

cspapp/templates/cspapp/activities_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Activities</title>
</head>
<body>
    <h1>Activities
        (<a href="{% url 'cspapp:activity_create' %}">add</a>)
    </h1>
    {% if activities %}
        <ul>
        {% for activity in activities %}
        <li>
            <h4>
            <a href="{% url "cspapp:activities_detail" activity.id%}"> {{activity.title}}</a>
            by {{ activity.user }} </h4>
            <h4>{{ activity.description }}</h4>

            <br>
        {% endfor %}
        </ul>
        {%  else %}
            <h3>No hi ha activitats encara</h3>
    {% endif %}

    <br>
    <a href='/'> Home </a>

</body>
</html>

cspapp/templates/cspapp/activity_detail.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/cspapp.css' %}" />

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ activity.title }}</title>
</head>
<body>
<div id="header">
    <div> <img src="/static/css/images/Logo.jpg" align="left"> </div>
    <h1><a href="/">UDL Citizen Science Platform</a></h1>
</div>
    <br>
    <hr>

<nav>
<ul id="sidebar">
    <li><a id="greyfonts" href='/'> Home </a></li>
    <hr>
    <li><a id="greyfonts" href='/cspapp/projects/'> More projects </a></li>
    <hr>
    <li id="greyfonts"> Back to: </li>
    <li><a id="greyfonts" href="{% url "cspapp:projects_detail" activity.project%}"> {{ activity.project.name }} </a></li>
</ul>
</nav>

<div id="content">
    <h2> {{ activity.project.name }} </h2>
    <h2>{{ activity.title }}
        {%  if user == activity.user  %}
            (<a href="{% url 'cspapp:activity_edit' object.id %}">edit</a>)
            (<a class="marge" href="{% url 'delete_activity' object.id %}" class="top-menu">Delete  <span class="glyphicon glyphicon-minus"></span></a>)
        {% endif %}
    </h2>
    <h3>{{ activity.description }}</h3>
    <p>{{ activity.statement }}</p>

    <form action="{% url 'cspapp:answer_create' activity.id %}" method="post">
    {% csrf_token %}
    Answer: <textarea name="comment" id="comment" rows="8" cols="50"></textarea>

    </p>
    <input type="submit" value="Answer" />

    <p>Author: {{ activity.user }}</p>
    </form>

    <h2 id="stdnavy">Answers</h2>

    <table>
      <tr>
        <th style="width:150px">User</th>
        <th style="width:500px">Answer</th>
        <th style="width:100px">Date</th>
      </tr>

        {% for answer in object.activityanswer_set.all %}

            <tr>
            {%  if user.id == answer.user_id or user == activity.user  %}
                <td style="width:150px">
                    <p><b>{{ answer.user }}:</b>
                    {% if user == answer.user %}
                        <a href="{% url 'delete_answer' answer.id %}">Delete</a>
                    {%  endif %}
                    </p></td>
                    <td style="width:500px"><p>{{ answer.body }}</p></td>
                    <td style="width:100px"><p>{{ answer.date }}</p></td>
                </td>
            {% endif %}
            </tr>
        {% endfor %}

    </table>

    <p>&#169; PBA&Q Group</p>

</div>
</body>
</html>

cspapp/templates/cspapp/base.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/cspapp.css' %}" />

<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">

<head>
    <title>Base Citizen Science Platform UDL</title>
</head>

<body>

<div id="header">
    <div> <img src="/static/css/images/Logo.jpg" align="left"> </div>
    <h1><a href="/">UDL Citizen Science Platform</a></h1>
</div>
    <br>
    <hr>

<nav>
<ul id="sidebar">
    <li><a id="greyfonts" href='/'> Home </a></li>
    {% block header %}
        {% if user.username %}
            <li id="greyfonts"> Logged as: <b>{{ user.username }} </b></li>
            <li><a id="greyfonts" href="{% url 'logout' %}?next={{request.path}}">Logout</a></li>
        {% else %}
            <li><a id="greyfonts" href="{% url 'login' %}?next={{request.path}}">Login</a></li>
            <li><a id="greyfonts" href="{% url 'register' %}"  class="top-menu">Sign up<span class="glyphicon glyphicon-plus"></span></a></li>
        {% endif %}
    {% endblock %}

    <li><a id="greyfonts" href="http://127.0.0.1:8000/admin">Admin</a></li>
</ul>
</nav>

<div id="content">
    {% block project_list %}
    <h2><a href="/cspapp/projects">Projects list</a></h2>
    {% endblock %}
</div>

</body>
</html>

cspapp/templates/cspapp/form.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/cspapp.css' %}" />

<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">

<head>
    <title>Project creation</title>
</head>

<body>

<div id="header">
    <div> <img src="/static/css/images/Logo.jpg" align="left"> </div>
    <h1><a href="/">UDL Citizen Science Platform</a></h1>
</div>
    <br>
    <hr>

<nav>
<ul id="sidebar">
    <li><a id="greyfonts" href='/'> Home </a></li>
</ul>
</nav>

<div id="content">
{% block content %}
    <form method="post" enctype="multipart/form-data" action="">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit"/>
    </form>
{% endblock %}
</div>

cspapp/templates/cspapp/principal.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/cspapp.css' %}" />

<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">

    <head>
    <title>Principal Citizen Science Platform UDL</title>
    </head>

<body>

<div id="header">
    <div> <img src="/static/css/images/Logo.jpg" align="left"> </div>
    <h1>UDL Citizen Science Platform</h1>
</div>
    <br>
    <hr>

<nav>
<ul id="sidebar">
    {% block header %}
        {% if user.username %}
            <li id="greyfonts">Logged as: <b>{{ user.username }} </b> <a id="greyfonts" href="{% url 'logout' %}?next={{request.path}}">Logout</a></li>
        {% else %}
            <li><a id="greyfonts" href="{% url 'login' %}?next={{request.path}}">Login</a></li>
            <li><a id="greyfonts" href="{% url 'register' %}"  class="top-menu">Sign up<span class="glyphicon glyphicon-plus"></span></a></li>
        {% endif %}
    {% endblock %}

    <li><a id="greyfonts" href="http://127.0.0.1:8000/admin">Admin</a></li>
    <hr>
    <li><a id="greyfonts" href="/cspapp/projects">Projects list</a></li>
    <li><a id="greyfonts" href="/cspapp/users">Users list</a></li>
</ul>
</nav>

<div id="content">

    <img src="/static/css/images/eps.png" alt="UDL Icon" >
    <p></p>
    <h2 id="stdnavy">Welcome to UDL Citizen Science Platform (CSP)</h2>
      <div class="transbox">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin laoreet tortor at orci placerat tincidunt. Fusce malesuada magna ac nunc tempor, in faucibus ligula convallis. Nunc ac erat varius, consequat lorem et, egestas est. Donec ultrices ligula eu rhoncus hendrerit. Proin nec lorem pharetra, hendrerit magna quis, condimentum mi. Nam risus elit, auctor sit amet rutrum sed, lacinia vitae velit. Maecenas ac consectetur lectus. Aenean id ipsum iaculis nunc placerat interdum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

        Praesent mattis pharetra justo, ut scelerisque diam lobortis et. Donec a nunc eros. Integer pharetra fringilla massa ac consequat. Maecenas laoreet varius viverra. Aliquam erat volutpat. Pellentesque augue velit, volutpat ac consectetur ac, tempus vel ligula. Maecenas enim turpis, ornare quis placerat et, ultricies eu nulla. Aliquam sed erat in urna euismod fermentum. Donec ut lacus non ex maximus eleifend. Maecenas congue nibh ac dapibus dignissim. Quisque pulvinar felis sit amet felis lacinia consequat. Etiam mattis cursus lobortis. Nulla lobortis nibh vitae est consequat, in vestibulum libero suscipit.

        Mauris sagittis lacus at mollis egestas. Maecenas vehicula a augue ac aliquam. Maecenas interdum ante sit amet sollicitudin gravida. Pellentesque sit amet venenatis lorem, a pellentesque sapien. Donec placerat non turpis eu facilisis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi velit turpis, fermentum non scelerisque ac, consequat in ipsum. Duis vel rutrum ligula. Integer at cursus justo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc mattis nisl quam, id accumsan arcu feugiat sed. Duis ac faucibus elit. Etiam consectetur erat eleifend est ornare feugiat. Maecenas sed orci nulla. Sed ultricies tempus fermentum. Sed a pulvinar leo.

        Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla non felis egestas felis aliquam luctus. Aenean id consectetur erat, vel aliquet diam. Ut at neque risus. Quisque luctus imperdiet magna et viverra. Vestibulum rutrum dui vel erat posuere cursus in non dolor. Mauris malesuada, purus ac vulputate hendrerit, nisi velit ultrices odio, quis sagittis turpis tortor sit amet mi. Nunc augue risus, ultrices convallis sollicitudin ac, auctor finibus diam. Curabitur quis sodales lacus. Curabitur rutrum purus id venenatis porta. Curabitur convallis, velit vel pellentesque aliquet, ligula quam sollicitudin quam, sit amet scelerisque lacus magna malesuada orci. Phasellus maximus ipsum ut augue egestas, eget finibus purus efficitur. Ut vehicula ligula fringilla iaculis molestie. Integer imperdiet dui semper, iaculis lorem sit amet, vulputate dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus mauris libero, ultrices id ligula at, sodales sollicitudin metus.

        In efficitur cursus magna, sed bibendum elit ultrices pulvinar. Donec vestibulum id mauris quis ornare. Nulla eu dui vel ligula fermentum euismod et nec velit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum quis lorem malesuada nisl aliquet tincidunt nec a purus. Duis quam justo, luctus a erat sed, feugiat laoreet velit. Curabitur cursus urna a tincidunt venenatis. Quisque eleifend elit pretium odio sollicitudin, in dignissim tortor mattis. Nullam maximus consequat risus, ac tempus lectus suscipit in. Vestibulum quis euismod nisi.</p>

      </div>
<p>&#169; PBA&Q Group</p>

</div>

</body>
</html>

cspapp/templates/cspapp/projects_detail.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/cspapp.css' %}" />

<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">

    <head>
    <title>Pro. Details Base Citizen Science Platform UDL</title>
    </head>

<body>

<div id="header">
    <div> <img src="/static/css/images/Logo.jpg" align="left"> </div>
    <h1><a href="/">UDL Citizen Science Platform</a></h1>
</div>
    <br>
    <hr>

<nav>
<ul id="sidebar">
    <li><a id="greyfonts" href='/'> Home </a></li>
    <li><a id="greyfonts" href='/cspapp/projects/'> More projects </a></li>
    <li><a id="greyfonts" href="{% url 'cspapp:activity_create' object.id %}">Add Activities</a></li>
    <hr>
     <li id="greyfonts"> Activities: </li>


    {% for activity in object.projectactivity_set.all %}
        <li><a id="greyfonts" href="{% url "cspapp:activities_detail" activity.id%}"> {{activity.title}} </a></li>
    {% endfor %}

</ul>
</nav>

<div id="content">
    <title>{{project.name}}</title>
    <h2 id="stdnavy">{{project.name}}

        {% if project.developers_id == request.user.id %}
            (<a href="{% url 'cspapp:project_edit' object.id %}">edit</a>)
            (<a class="marge" href="{% url 'delete_project' project.id %}" class="top-menu">Delete  <span class="glyphicon glyphicon-minus"></span></a>)
        {% endif %}
    </h2>

    {%	if	project.image	%}
        <p><img	src="{{project.image.url}}" width="300px"/></p>
    {%	endif	%}
    <li id="stdnavy"> <b>Description:</b> {{ object.description }} </li>
    <li id="stdnavy"> <b>Department:</b> {{ object.department.name }} </li>
    <li id="stdnavy"> <b>Developers:</b> {{ object.developers }} </li>
    <li id="stdnavy"> <b>Link:</b> <a href="{{object.link}}" target="_blank"  > {{object.link}} </a> </li>



<h4 id="stdnavy">Add Comment</h4>
<form action="{% url 'cspapp:review_create' project.id %}" method="post">
    {% csrf_token %}
    Message: <textarea name="comment" id="comment" rows="4"></textarea>
    <p>Rating:</p>
    <p>{% for rate in RATING_CHOICES %}
    <input type="radio" name="rating" id="rating{{ forloop.counter }}" value="{{ rate.0 }}" />
    <label for="choice{{ forloop.counter }}">{{ rate.1 }} star{{ rate.0|pluralize }}</label>
    <br/>{% endfor %}
    </p>
    <input type="submit" value="Review" />
</form>

<h2 id="stdnavy">Comments</h2>

<table>
  <tr>
    <th>Writer</th>
    <th>&#9733;</th>
    <th>Comment</th>
    <th>Date</th>
  </tr>

    {% for review in object.projectreview_set.all %}

         <tr>
         <td style="width:100px">{{ review.user }}
         {% if user.username == "moderator" or review.user == user%}
             <a href="{% url 'delete_comment' review.id %}">Delete</a>
         {%  endif %}
         </td>
         <td style="width:50px"; align="center">{{ review.rating }}</td>
         <td style="width:400px">{{ review.comment }}</td>
         <td style="width:100px">{{ review.date }}</td>
        </tr>

    {% endfor %}

</table>

<p>&#169; PBA&Q Group</p>

</div>
</body>
</html>

cspapp/templates/cspapp/projects_list.html
<html>
  <head>
    <title> Projects </title>

      <script
 	src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js">
 	</script>

 	<link rel="stylesheet"
 	href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">

  	<script
  	src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>


  </head>
  {% extends "cspapp/base.html" %}
  <body>
  <div id="content">
     {% block project_list %}
     <h2 id="stdnavy">Projects
       (<a href="{% url 'cspapp:project_create' %}">add</a>)
     </h2>


        <style>

          .divisor{

              display: table;
              margin: 0 auto;
              margin-top: 50px;
          }

	    </style>

        <script>
            $(function(){
                var genre = [
                    "Best project ever",
                    "New one",
                    "Other one",


                ];
                $( "#groups_auto" ).autocomplete({
                    source: genre
                });

            });
        </script>

         <div class="divisor">
                <label for="tags">Search for project: </label>
                <input id="groups_auto">
                <button onclick="myFunction(groups_auto.value)">Go to project</button>

         </div>
    <script>

    function myFunction(PROJECT) {

        if (PROJECT == "Best project ever")
         window.location="http://127.0.0.1:8000/cspapp/projects/1";

        if (PROJECT == "New one")
         window.location="http://127.0.0.1:8000/cspapp/projects/2";

        if (PROJECT == "Other one")
         window.location="http://127.0.0.1:8000/cspapp/projects/3";
    }
    </script>


     {% if projects %}
    <ul id="projectlist">
    {% for project in projects %}
    <li>
    <a href="{% url "cspapp:projects_detail" project.id%}"> {{project.name}} </a>
    </li>

    <!-- </li><a class="marge" href="{% url 'delete_project' project.id %}" class="top-menu">Delete  <span class="glyphicon glyphicon-minus"></span></a> -->

    {% endfor %}
    </ul>
    {% else %}
    <p style="text-indent: 2em">Any project yet</p>
    {% endif %}
    <a href='/'> Home </a>
     {% endblock %}
    <br>
      <a href='/'> Home </a>
  </div>
  </body>
</html>

cspapp/templates/cspapp/users_list.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/cspapp.css' %}" />

<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">

<head>
    <title>Users_List Base Citizen Science Platform UDL</title>

    <script
 	src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js">
 	</script>

 	<link rel="stylesheet"
 	href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">

  	<script
  	src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

    <style>

	  .divisor{

	      display: table;
          margin: 0 auto;
          margin-top: 50px;
	  }

	</style>

</head>

<body>

<div id="header">
    <div> <img src="/static/css/images/Logo.jpg" align="left"> </div>
    <h1><a href="/">UDL Citizen Science Platform</a></h1>
</div>
    <br>
    <hr>

<nav>
<ul id="sidebar">
    <li><a id="greyfonts" href='/'> Home </a></li>
    {% block header %}
        {% if user.username %}
            <li id="greyfonts"> Logged as: <b>{{ user.username }} </b></li>
            <li><a id="greyfonts" href="{% url 'logout' %}?next={{request.path}}">Logout</a></li>
        {% else %}
            <li><a id="greyfonts" href="{% url 'login' %}?next={{request.path}}">Login</a></li>
            <li><a id="greyfonts" href="{% url 'register' %}"  class="top-menu">Sign up<span class="glyphicon glyphicon-plus"></span></a></li>
        {% endif %}
    {% endblock %}

    <li><a id="greyfonts" href="http://127.0.0.1:8000/admin">Admin</a></li>
</ul>
</nav>


<script>

        $(function(){
            var genre = [
                "admin",
                "user1",
                "user2",
                "moderator",
                "troll_student_XD",
                "qwer",
                "josep555",

            ];
            $( "#groups_auto" ).autocomplete({
                source: genre
            });

        });


    </script>
<div id="content">

                <h2 id="stdnavy">Users search</h2>
                <input id="groups_auto">
                <button onclick="myFunction(groups_auto.value)">Search</button>



    <script>
    function myFunction(USERNAME) {

            window.location="http://127.0.0.1:8000/profile/"+USERNAME;


    }
    </script>





    <<h2 id="stdnavy">Users List:</h2>
<ul id="projectlist">
         {% for user in users %}


<li><a id="list" href="{% url 'profile'  user.id  %}"> {{ user.username }} </a></li>

          {% endfor %}

</ul>
</div>


</body>
</html>